default_shell: zsh
pane_frames: false
copy_command: "wl-copy"

        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'h', Char: "\n", Char: ' ', Esc]
keybinds:
    unbind: [ Char: 'h',
            Char: 'j',
            Char: 'k',
            Char: 'l',
            Char: 'n',
            Char: 'e',
            Char: 'i', #Unused by default
            Char: 'o',
            Ctrl: 'b',
            Ctrl: 'q',
            Alt: 'q',  #Unused by default
            # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
            Alt: 'h',
            Alt: 'j',
            Alt: 'k',
            Alt: 'l',
            Alt: 'n',
            Alt: 'e',  #Unused by default
            Alt: 'i',  #Unused by default
            Alt: 'o'   #Unused by default
          ]
    normal:
        - action: [SwitchToMode: Tmux,]
          key: [Alt: 'q',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'n', Alt: Left]
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'e', Alt: Right ]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'i', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'o', Alt: Up, ]
    resize:
        - action: [SwitchToMode: Tmux,]
          key: [Alt: 'q',]
        - action: [Resize: Left,]
          key: [Char: 'n', Left,]
        - action: [Resize: Down,]
          key: [Char: 'e', Down,]
        - action: [Resize: Up,]
          key: [Char: 'i', Up, ]
        - action: [Resize: Right,]
          key: [Char: 'o', Right,]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'n', Alt: Left]
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'e', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'i', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'o', Alt: Up]
    pane:
        - action: [SwitchToMode: Tmux,]
          key: [Alt: 'q',]
        - action: [MoveFocus: Left,]
          key: [ Char: 'n', Left,]
        - action: [MoveFocus: Right,]
          key: [ Char: 'e', Right,]
        - action: [MoveFocus: Down,]
          key: [ Char: 'i', Down,]
        - action: [MoveFocus: Up,]
          key: [ Char: 'o', Up,]
        - action: [NewPane: , SwitchToMode: Normal,]
          key: [Char: 'h',]
        - action: [TogglePaneEmbedOrFloating, SwitchToMode: Normal,]
          key: [Char: 'l']
        - action: [NewPane: ,]
          key: [ Alt: 'h',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
    move:
        - action: [MovePane: ,]
          key: [Char: 'h', Char: "\t",]
        - action: [MovePane: Left,]
          key: [Char: 'n', Left,]
        - action: [MovePane: Down,]
          key: [Char: 'e', Down,]
        - action: [MovePane: Up,]
          key: [Char: 'i', Up, ]
        - action: [MovePane: Right,]
          key: [Char: 'o', Right,]
        - action: [NewPane: ,]
          key: [ Alt: 'h',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
    tab:
        - action: [SwitchToMode: Tmux,]
          key: [Alt: 'q',]
        - action: [GoToPreviousTab,]
          key: [ Char: 'n', Left, Up, Char: 'i',]
        - action: [GoToNextTab,]
          key: [ Char: 'e', Right,Down, Char: 'o']
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'n',]
        - action: [NewPane: ,]
          key: [ Alt: 'h',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
        # - action: [Resize: Increase,]
    scroll:
        - action: [EditScrollback, SwitchToMode: Normal]
          key: [Char: 'v']
        - action: [SwitchToMode: Tmux,]
          key: [Alt: 'q',]
        - action: [ScrollDown,]
          key: [Char: 'e', Down,]
        - action: [ScrollUp,]
          key: [Char: 'i', Up,]
        - action: [PageScrollDown,]
          key: [Ctrl: 'f', PageDown, Right, Char: 'o',]
        - action: [PageScrollUp,]
          key: [Ctrl: 'b', PageUp, Left, Char: 'n',]
        - action: [NewPane: ,]
          key: [ Alt: 'n',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]  # The Alt: Left etc. variants are temporary hacks and will be removed in the future - please do not rely on them!
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
    renametab:
        - action: [NewPane: ,]
          key: [ Alt: 'h',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
    renamepane:
        - action: [NewPane: ,]
          key: [ Alt: 'h',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
    session:
        - action: [SwitchToMode: Tmux,]
          key: [Alt: 'q',]
        - action: [NewPane: ,]
          key: [ Alt: 'h',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
    tmux:
        - action: [SwitchToMode: Locked,]
          key: [Ctrl: 'g']
        - action: [SwitchToMode: Resize,]
          key: [Ctrl: 'n',]
        - action: [SwitchToMode: Pane,]
          key: [Ctrl: 'p',]
        - action: [SwitchToMode: Move,]
          key: [Ctrl: 'h',]
        - action: [SwitchToMode: Tab,]
          key: [Ctrl: 't',]
        - action: [SwitchToMode: Normal,]
          key: [Ctrl: 'o', Char: "\n", Char: ' ', Esc]
        - action: [SwitchToMode: Scroll,]
          key: [Ctrl: 's']
        - action: [SwitchToMode: Scroll,]
          key: [ Char: '[']
        - action: [Quit,]
          key: [Ctrl: 'q',]
        - action: [Write: [2,], SwitchToMode: Normal]
          key: [Alt: 'q']
        - action: [NewPane: Down, SwitchToMode: Normal,]
          key: [Char: "\"",]
        - action: [NewPane: Right, SwitchToMode: Normal,]
          key: [Char: '%',]
        - action: [ToggleFocusFullscreen, SwitchToMode: Normal,]
          key: [Char: 'z',]
        - action: [NewTab: , SwitchToMode: Normal,]
          key: [ Char: 'c',]
        - action: [SwitchToMode: RenameTab, TabNameInput: [0],]
          key: [Char: ',']
        - action: [GoToPreviousTab, SwitchToMode: Normal,]
          key: [ Char: 'p']
        # - action: [GoToNextTab, SwitchToMode: Normal,]
        #   key: [ Char: 'n']
        - action: [MoveFocus: Left, SwitchToMode: Normal,]
          key: [ Left,]
        - action: [MoveFocus: Right, SwitchToMode: Normal,]
          key: [ Right,]
        - action: [MoveFocus: Down, SwitchToMode: Normal,]
          key: [ Down,]
        - action: [MoveFocus: Up, SwitchToMode: Normal,]
          key: [ Up,]
        # - action: [MoveFocus: Left, SwitchToMode: Normal,]
        #   key: [ Char: 'h']
        # - action: [MoveFocus: Right, SwitchToMode: Normal,]
        #   key: [ Char: 'l']
        # - action: [MoveFocus: Down, SwitchToMode: Normal,]
        #   key: [ Char: 'j']
        # - action: [MoveFocus: Up, SwitchToMode: Normal,]
        #   key: [ Char: 'k']
        # - action: [NewPane: ,]
        #   key: [ Alt: 'n',]
        # - action: [MoveFocusOrTab: Left,]
        #   key: [ Alt: 'h', Alt: Left]
        # - action: [MoveFocusOrTab: Right,]
        #   key: [ Alt: 'l', Alt: Right]
        # - action: [MoveFocus: Down,]
        #   key: [ Alt: 'j', Alt: Down]
        # - action: [MoveFocus: Up,]
        #   key: [ Alt: 'k', Alt: Up]
        # - action: [FocusNextPane,]
        #   key: [ Char: 'o']
        - action: [Resize: Increase,]
          key: [ Alt: '=']
        - action: [Resize: Increase,]
          key: [ Alt: '+']
        - action: [Resize: Decrease,]
          key: [ Alt: '-']
        - action: [Detach,]
          key: [Char: 'd',]
